openapi: "3.0.0"
info:
  title: "Ice-cream Parlor: Menu API"
  version: "1.0"

servers:
  - url: https://localhost

paths:

  /menu/v1/healthcheck:
    get:
      responses:
        '200':
          description: This is always returned

  /menu/v1/products:

    get:
      summary: Return the full menu with all existing products
      responses:
        '200':
          description: The full menu
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

    post:
      summary: Add a new ice-cream product
      requestBody:
        description: The product composition
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        '201':
          description: The created product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

  /menu/v1/product/{id}:

    get:
      summary: Return an existing ice-cream product
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Product id
      responses:
        '200':
          description: The product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        '404':
          description: Product not found

    delete:
      summary: Delete given ice-cream product
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Product id
      responses:
        '200':
          description: Product deleted
        '204':
          description: Product not found

  /menu/v1/cone:

    get:
      summary: Return all existing cones
      responses:
        '200':
          description: All existing cones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cone"

    post:
      summary: Add a new cone
      requestBody:
        required: true
        description: Cone, without an ID
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cone"
      responses:
        '201':
          description: The created cone
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cone"

  /menu/v1/cone/{id}:

    get:
      summary: Return an existing cone type
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Cone id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cone"
        '404':
          description: Cone not found

    delete:
      summary: Delete given cone
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Cone id
      responses:
        '200':
          description: Cone deleted
        '204':
          description: Cone not found
        '409':
          description: Won't delete because cone is referenced in a product

  /menu/v1/flavor:

    get:
      summary: Return all flavors
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Flavor"

    post:
      summary: Add a new flavor
      requestBody:
        required: true
        description: Flavor, without an ID
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Flavor"
      responses:
        '201':
          description: The created flavor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Flavor"


  /menu/v1/flavor/{id}:

    get:
      summary: Return an existing flavor
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Flavor id
      responses:
        '200':
          description: The flavor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Flavor"
        '404':
          description: Flavor not found

    delete:
      summary: Delete given flavor
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Flavor id
      responses:
        '200':
          description: Flavor deleted
        '204':
          description: Flavor not found
        '409':
          description: Won't delete because flavor is referenced in a product

  /menu/v1/topping:

    get:
      summary: Return all toppings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Topping"

    post:
      summary: Add a new topping
      requestBody:
        required: true
        description: Topping, without an ID
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Topping"
      responses:
        '201':
          description: Created topping
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Topping"

  /menu/v1/topping/{id}:

    get:
      summary: Return an existing topping
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Topping id
      responses:
        '200':
          description: The topping
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Topping"
        '404':
          description: Topping not found

    delete:
      summary: Delete given topping
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Topping id
      responses:
        '200':
          description: Topping deleted
        '204':
          description: Topping not found
        '409':
          description: Won't delete because topping is referenced in a product

components:
  schemas:
    Cone:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
        name:
          type: string
      example:
        id: 123
        name: "waffle"
    Flavor:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
        name:
          type: string
      example:
        id: 123
        name: "chocolate"
    Topping:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
        name:
          type: string
      example:
        id: 123
        name: "chocolate sprinkles"
    Product:
      type: object
      required:
        - name
        - cone
        - flavor
      properties:
        id:
          type: integer
        name:
          type: string
        cone:
          $ref: "#/components/schemas/Cone"
        flavor:
          $ref: "#/components/schemas/Flavor"
        toppings:
          type: array
          items:
            $ref: "#/components/schemas/Topping"
