FROM nginx:latest

RUN apt update
RUN apt install -y certbot
RUN certbot certonly --manula --preferred-challenges=dns --server https://acme-v02.api.letsencrypt.org/directory --agree-tos -d *.catsoft.com

CMD ["nginx", "-g", "daemon off;"]